name-template: 'Release ${{ version }}'
tag-template: 'v{{ version }}'
categories:
  - title: 'ğŸš€ New Features'
    labels: ['feature']
  - title: 'ğŸ› Bug Fixes'
    labels: ['bug']
  - title: 'ğŸ”§ Improvements'
    labels: ['enhancement']
change-template: '- ${{ change }} (#${{ number }})'
template: |
  ## Changes in this release
  $CHANGES
